### ISSUE TITLE
Make django-leaflet widget in admin

### ISSUE THREAD

**Issue by pirr** [makinacorpus/django-leaflet#107]
I'm sorry if I use wrong way (I have recently been studying Django).
Can I make leaflet-django widget in admin?

my model:
from django.contrib.gis.db import models as m
from djgeojson.fields import GeometryCollectionField

class Doc(m.Model):
      name = m.CharField()
      type = m.ForeignKey()
      geom = GeometryCollectionField()

admin:
class DocAdmin(admin.ModelAdmin):
     form = f.DocGeometryForm
     ...

form:
from leaflet.forms.widgets import LeafletWidget
class DocGeometryForm(f.ModelForm):
    class Meta:
        model = m.Doc
        widgets = {
          'geom': LeafletWidget(),
        }

    class Media:
        css = {
            'all':('ext/leaflet/leaflet.css',)
        }
        js = [
            'ext/jquery/jquery.js',
            'ext/leaflet/leaflet.js',
        ]

But in console I getting: l.map.djangomap is not a function

**Comment by leplatrem** [comment]
Did you try what is described in the README using LeafletGeoAdmin ?

**Comment by pirr** [comment]
Yes I had read... I wanted to make leafletadmin through modelform. Now I think it was bad decision. I close this issue. Sorry for my amateurism.

**Comment by leplatrem** [comment]
Never be sorry for that !
