### ISSUE TITLE
Field name with spaces or other chars breaks input

### ISSUE THREAD

**Issue by josemazo** [makinacorpus/django-leaflet#123]
If your field has a space in the name, like "Ending position", or other chars like an apostrophe, it will break the input (widget) because it can't create proper JavaScript variable names.

P.S.: Thanks for this amazing Django app guys!

**Comment by leplatrem** [comment]
Thanks for this feedback !

That's sounds like a reasonably easy fix, do not hesitate to submit a pull-request!


---------
*We would welcome any help for maintaining this library. If you use it and find it useful, please* Watch *it on Github, help us review contributions or comment issues :) Thousand thanks in advance.*
