### ISSUE TITLE
Change `loadevent` in widgets

### ISSUE THREAD

**Issue by josemazo** [makinacorpus/django-leaflet#125]
I am trying to change the `loadevent` in the widgets. I've found two options in your docs:

- In the `{% leaflet_map %}` tag, but this isn't for widgets.
- Dispatching a JS event (`loadLeafletMap`) and creating the widget like this:

```python
LeafletWidget(attrs={
   'loadevent': 'loadLeafletMap'
})
```

Does the second one should work? Because it isn't working for me :disappointed:

**Comment by leplatrem** [comment]
Hi,

I haven't used the project for a while, and can't really dig into this unfortunately...

From what I see here: https://github.com/makinacorpus/django-leaflet/blob/c53f3039e77adf383bc877792f4ffb16206b4d6f/leaflet/templates/leaflet/widget.html#L40

The `loadevent` argument is not passed along using the widget.

Don't hesitate to submit a pull-request with some changes for that, we can review and guide you to achieve what you want!

Thanks for the feedback!

---------
*We would welcome any help for maintaining this library. If you use it and find it useful, please* Watch *it on Github, help us review contributions or comment issues :) Thousand thanks in advance.*

**Comment by leplatrem** [comment]
Fixed in #127
