### ISSUE TITLE
New feature: Do not generate any tile layers

### ISSUE THREAD

**Issue by dyve** [makinacorpus/django-leaflet#144]
I have some projects where I always want to initialize the tile layers and/or overlays in my own JavaScript code. Setting TILES to False results in the default OpenStreetMap layer being created. I'm proposing that empty list bee a valid setting for TILES, and that django-leaflet will not generate a tile layer when it sees that value. Pull request coming up.

**Comment by mcdlee** [comment]
I met the same problem and I found that the LEAFLET_CONFIG section in settings.py is must filled, at least 'SPATIAL_EXTENT'.
