### ISSUE TITLE
MultipolygonField widget will not respond to touch event

### ISSUE THREAD

**Issue by raratiru** [makinacorpus/django-leaflet#156]
Using django 1.9 admin interface on Firefox when I use the MultipolygonField widget and click around, it works as expected.

However, when I try to work on a Samsung tablet using either Chrome or Firefox or the native browser, although I can select the tool to start drawing the polygon, it is impossible to place any point on the map. 

Seems like it does not respond to touch event.

**Comment by jieter** [comment]
As mentioned in [this SO answer](http://stackoverflow.com/a/37918834/517560), this needs leaflet-draw 0.3.0 which is achieved by merging #153

**Comment by leplatrem** [comment]
Leaflet draw v0.4.0 is out. Please open a pull-request with this stable release

**Comment by Gagaro** [comment]
draw 0.4.9 has been merged (#179).
