### ISSUE TITLE
From 0.18 to 0.18.1, my map dissapears

### ISSUE THREAD

**Issue by typeshige** [makinacorpus/django-leaflet#158]
When I upgraded to 0.18.1, a gray box appears in the map area.  Going back to 0.18 restores the map.

Please let me know if you have any ideas or things to try.

Thanks.

**Comment by raratiru** [comment]
I found out that a grey box appears when the zoom is set over 18. 

Zooming out, the map reappears.

This is just a hint.

**Comment by akbargumbira** [comment]
Yeah, I had this problem too in my django apps https://github.com/akbargumbira/django-user-map/. I think I will just freeze the version in the setup of my app for pip..

**Comment by maltem-za** [comment]
Same problem here

**Comment by leplatrem** [comment]
I just created a sample project, just works. Have a look at #168 and reopen if relevant.

Might be related to #167 though.
