### ISSUE TITLE
Form edit zoom level is not the maximum possible

### ISSUE THREAD

**Issue by seav** [makinacorpus/django-leaflet#165]
Early last year, a pull request (#95) was merged in order to avoid a hangup issue (#90) in Leaflet when editing a geometry form field. This has the side effect that if the geometry is just a point, the zoom level is not the maximum possible and depending on how django-leaflet is configured the map could be set to zoom level 0.

I tried undoing the PR #95 changes and I get the expected behavior: the zoom level is the maximum possible (so `fitBounds()` works as expected). Furthermore, I don't encounter the hangup mentioned in #90. I think that having a later Leaflet version has fixed the hangup issue and so the #95 workaround is no longer needed.

**Comment by leplatrem** [comment]
Thanks @seav for the feedback.

If you think #95 should be undone, please open a PR that applies the revert!
