### ISSUE TITLE
Problem with Django 1.10

### ISSUE THREAD

**Issue by izaguerreiro** [makinacorpus/django-leaflet#181]
The icons don't load and the point (marker) doesn't save in map.

**Comment by Gagaro** [comment]
Do you have `gdal-bin` (or your distribution equivalent) installed? I realized earlier that it was a requirements (you probably have an error in the django log about it).

**Comment by izaguerreiro** [comment]
I installed gdal-bin, but it continues the same way. This problem happens in django admin.

**Comment by arybin93** [comment]
I have the problem for Django 1.9.7 
My polygons saved, but after don't show points

**Comment by W7PEA** [comment]
Anytime I've had an issue where the map in admin doesn't show the data, but my templates did, it was because I had not run `python manage.py collectstatic`. Not 100% sure that is your issue, but I mention it because just today I had to do that.

**Comment by claudep** [comment]
I guess this was a configuration error, I suggest to close it.
