### ISSUE TITLE
django-leaflet with Whitenoise messes up marker-icon.png and marker-shadow.png

### ISSUE THREAD

**Issue by Matbj** [makinacorpus/django-leaflet#188]
I'm using Whitenoise for static file serving (because reasons) and I think that the regex that is being used here:
.../staticfiles/leaflet/leaflet-src.js:6325
```path.replace(/^url\([\"\']?/, '').replace(/marker-icon\.png[\"\']?\)$/, '') : '';```
messes up when used with Whotenoise because it tries to fetch the file like this:
```
"GET /static/leaflet/images/marker-icon.2273e3d8ad92.png%22)marker-icon.png HTTP/1.1" 404 146 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
"GET /static/leaflet/images/marker-icon.2273e3d8ad92.png%22)marker-shadow.png HTTP/1.1" 404 148 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
```

**Comment by xusy2k** [comment]
Same problem here, it's not django-leaflet's bug. It comes from Leaflet.

For fixing it's enough replacing at line 
```javascript 
return path.indexOf('url') === 0 ?
            path.replace(/^url\([\"\']?/, '').replace(/marker-icon\.png[\"\']?\)$/, '') : '';
```
for this new one:

```javascript 
return path.indexOf('url') === 0 ?
            path.replace(/^url\([\"\']?/, '').replace(/marker-icon[\.[a-zA-Z0-9]*\.png[\"\']?\)$/, '') : '';
```

I'm very newbie with GIS, but I've done tests with my map with and without Whitenoise and it worked in both cases.

**Comment by Gagaro** [comment]
Merge in #197

**Comment by olawale1rty** [comment]
> 
> 
> Same problem here, it's not django-leaflet's bug. It comes from Leaflet.
> 
> For fixing it's enough replacing at line
> 
> ```js
> return path.indexOf('url') === 0 ?
>             path.replace(/^url\([\"\']?/, '').replace(/marker-icon\.png[\"\']?\)$/, '') : '';
> ```
> 
> for this new one:
> 
> ```js
> return path.indexOf('url') === 0 ?
>             path.replace(/^url\([\"\']?/, '').replace(/marker-icon[\.[a-zA-Z0-9]*\.png[\"\']?\)$/, '') : '';
> ```
> 
> I'm very newbie with GIS, but I've done tests with my map with and without Whitenoise and it worked in both cases.
I just deployed my application using heroku when i noticed this error but i cant find the leaflet file due to the fact that i am using django-leaflet and geodjango for my application. Please, i will appreciate if you have a way of going through this.

**Comment by xusy2k** [comment]
Hi @olawale1rty! 
The files you are looking for are located at this commit xusy2k/django-leaflet@4fbf80d06c288727ed1e990e951499220d515a3f, but right now they are merged into master.

Maybe you can keep an eye to #268 and its files, makinacorpus/django-leaflet@a90098d7dcdbbcdfed329300d568c9691da21860

**Comment by olawale1rty** [comment]
Thank you very much sir.

**Comment by faaizajaz** [comment]
Any reason this hasn't been merged yet? Quite a pain to manually make the fix in production.

**Comment by faaizajaz** [comment]
> No solutions for this issue?

You need to build leaflet from source yourself. See commits in: https://github.com/faaizajaz/django-leaflet

**Comment by faprietoml** [comment]
> > No solutions for this issue?
> 
> @faprietoml You need to build leaflet from source yourself. See commits in: https://github.com/faaizajaz/django-leaflet

Thank you

**Comment by claudep** [comment]
@faaizajaz can we see a diff of your patch on the non-minified leaflet source?

**Comment by faaizajaz** [comment]
> @faaizajaz can we see a diff of your patch on the non-minified leaflet source?

I based my patch on this PR: https://github.com/makinacorpus/django-leaflet/commit/a90098d7dcdbbcdfed329300d568c9691da21860

Unfortunately this needs to be done manually every time there is a new leaflet release (unless they have fixed it in the last month or so).

**Comment by claudep** [comment]
OK, then I think we could store the patch to `...-src.js` somewhere in django-leaflet source tree, then add a `README.upgrade` in leaflet/static/leaflet/ to document it (and a command to produce a minified version from the patched file). Then ideally a regression test should be added too, if possible.
