### ISSUE TITLE
translating actions

### ISSUE THREAD

**Issue by bekerov** [makinacorpus/django-leaflet#195]
Hello. Is possible specify translation text for this actions ?
Thanks
![image](https://user-images.githubusercontent.com/2405629/27252067-c4703b82-535d-11e7-984f-7ec8eae9520b.png)

**Comment by Gagaro** [comment]
Please see https://github.com/Leaflet/Leaflet.draw#customizing-language-and-text-in-leafletdraw

**Comment by bekerov** [comment]
Thank for your reply!
