### ISSUE TITLE
Leaflet 1.1.0 is out

### ISSUE THREAD

**Issue by Schumi09** [makinacorpus/django-leaflet#199]
Hi there,

just for your information: leaflet 1.1.0 was released two weeks ago.

http://leafletjs.com/2017/06/27/leaflet-1.1.0.html

Did you plan a new release already?

Best regards,
Schumi

**Comment by Gagaro** [comment]
Hi,

Not in the near future, unless someone do the PR and ensure everything works (there is a bug between leaflet 1.1.0 and leaflet.draw, see #198).

I'd also like to have leaflet 1.1.0, so if someone does the PR, I'll gladly merge it and do the release.

**Comment by W7PEA** [comment]
see PR #218

**Comment by Gagaro** [comment]
django-leaflet 0.24.0 has been released with Leaflet 1.3.1. Thanks @W7PEA for the PR.
