### ISSUE TITLE
Tile  loading in a view displaying multiple maps

### ISSUE THREAD

**Issue by frague59** [makinacorpus/django-leaflet#207]
Hi, 

I'm working on a django (**1.11.5**) view that displays multiple maps (**django-leaflet 0.22**) on the same page.
I assume that the same `Lieu` item can be loaded multiple times.

I've created a  templatetag named "render_map_lieu" that takes a `Lieu` as parameter, and contains the leaflet machinery to displays that map. `{% leaflet_css %}` and `{% leaflet_js %}` are loaded.

My templatetag: (Im using a randint to avoid same ids for multiple maps)
```python
@register.inclusion_tag('calendrier/tags/map.html')
def render_map_lieu(lieu):
    rnd = random.randint(0, 9999)

    map_id = 'id-map-lieu-%04d-%04d' % (lieu.pk, rnd)
    callback_name = 'initializeMap_%04d_%04d' % (lieu.pk, rnd)
    return {'debug': settings.CALENDRIER_TAGS_DEBUG,
            'lieu': lieu,
            'map_id': map_id,
            'callback_name': callback_name}
```

My template:
```html
{% load leaflet_tags %}
{% leaflet_map map_id callback=callback_name %}
<!--suppress JSUnusedLocalSymbols -->
<script type="text/javascript">
    var {{ callback_name }} = function ($map, options) {
        var geojson_map_url = '{% url "calendrier:maps:lieu_detail" pk=lieu.pk %}'; // Where lives the json data
        $.getJSON(geojson_map_url, function (data) {
            L.geoJson(data).addTo(map);
            var lng = data.features[0].geometry.coordinates[0];
            var lat = data.features[0].geometry.coordinates[1];
            $map.setView(new L.LatLng(lat, lng), 15);
        });
    };
</script>
```

The maps are shown in (bootstrap 3) modals.

The maps are initialized, except they don't display the full map: only a short part on the map is shown. When scrolling / zooming no it, some other parts of the map are loaded (can see it in the firefox dev tool), but nether the full map.

Thanks for your help !

**Comment by Gagaro** [comment]
Hi,

Does it works if you don't put it in a modal?

**Comment by frague59** [comment]
Hi, 

I've put the rendering code to the "main" view (aka. not in the modal), and it seems to work.

So, the modal is the problem... Have you any idea on how implement the map display in the modal ? 

Thanks !
