### ISSUE TITLE
Leaflet forms : Add Point items only

### ISSUE THREAD

**Issue by frague59** [makinacorpus/django-leaflet#209]
Hi, 

I'ld like to restrict the type on geom added to a leaflet map to Points only.

I've bound my model field to a djgeojson.fields.PointField, but the forms displays the Line / Area / Polygon / Point buttons at left.

## in models.py

```python

from djgeojson.fields import PointField

class Offer(models.Model):
   ...
   from_geom = PointField(verbose_name=_('from point'), null=True, blank=True)
```

## in forms.py
```python
class OfferCreateForm(forms.ModelForm):

    class Meta:
        model = models.Offer
        exclude = ()
        widgets = {from_geom': LeafletWidget}
```

How can I force leaflet to only display the **Point** button on form widget ? 
I think I'ld like set the `attrs` to the `LeafletWidget`, but I've not found any doc about that.

Thanks !

**Comment by Gagaro** [comment]
You should be able to override the widget type by setting the `geom_type` `attrs` of the widget (to `POINT`).

But it should already be the case if you have a `PointField` in your form.

**Comment by frague59** [comment]
OK, I've got it.

I don't see the link between the `PointField` and and the `LeafletWidget`: the model field is not bound to a widget : when I displays the form without any `widget` provided, I can see a blank textarea.

I've set a `PointField` in the model, but it is not defined in the form : I use the django magic about the ModelForm.

Thanks for your help !
