### ISSUE TITLE
Leaflet map "Tag Parameter" issue

### ISSUE THREAD

**Issue by xSoham** [makinacorpus/django-leaflet#220]
Hello! 
First of all let me thank you for this wonderful package of django-leaflet. I am a beginner in the django, leaflet framework and I am stuck in one particular field.
I am trying to update the map center with the help of the `settings_overrides` option and would like to override the default LEAFLET_CONFIG settings. So every time the map is loaded the center of the map would be dependent on the co-ordinates given in the data. However, I am not being able to figure out how the syntax for this template tag parameter would be. 

I have tried: 
 `{% leaflet_map "gis" settings_overrides={'DEFAULT_CENTER':(some_lat,some_long)} callback="window.our_layers" %}`

But this line actually throws an error.
This is actually an example with the hard coded co-ordinates, whereas I will be using a function to insert the center co-ordinate values based on the data imported. I have also tried various combinations of the line with different braces and quotation marks at different positions, but to no avail and I am getting an error. 

If someone can help me out with this issue, it would be great. 

Thanks

**Comment by cleder** [comment]
Have a look at https://github.com/cleder/os-opendata-edubase/blob/master/django/schools/templates/home.html#L71
or https://github.com/cleder/os-opendata-edubase/blob/master/django/schools/templates/assign.html#L238
This may not be the most elegant way, but it works for me.
HTH

**Comment by xSoham** [comment]
Hello,
Thank you so much for your reply. Forgive me for my ignorance and less knowledge in this field. But what I understood is that, you are saying that instead of updating the center through the Django-Leaflet, I do it through JavaScript. 
Honestly, I have tried the fitBounds and getBounds method. I am fetching the data through AJAX url call, but whenever I am trying to use the getBounds and fitBounds like given in here:
               ` map.fitBounds(os_open_layer.getBounds()); `
I am getting an error saying that the bounds are not valid. So I am in a bit of fix regarding this as well. If you could you give me any suggestions it would really help me out. 

Thanks in advance,
Soham

**Comment by phyominh** [comment]
I am also looking for an answer from similar situation. What I wanna do is search for a point, update the default centre from the point and pan from that centre if search for another point occurs. As @cleder sugggests, I added the code  `map.fitBounds(os_open_layer.getBounds());` but it kinda overrides the pan animation I set before. From #193 , @Gagaro suggested to override the template at https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/templates/leaflet/_leaflet_map.html but I am looking for a simpler solution, like a JS override.

**Comment by jeromecc** [comment]
[How to center a Leaflet Map forms in a Django template (SO anwer)](https://stackoverflow.com/questions/59819263/how-to-center-a-leaflet-map-forms-in-a-django-template)
```
<script type="text/javascript">
    window.addEventListener("map:init", function (e) {
        var detail = e.detail;
        detail.map.setView([{{user_lat}},{{user_lng}}], 10);
    }, false);

</script>
```
I couldn't find a way to pass settings_overrides as parameters directly in the template tag.

**Comment by OmenApps** [comment]
I know this is closed, but for anyone coming after the fact, there's a much simpler approach than doing this with js. Just pass the dictionary from the view and use it in the templatetag. For instance, assuming I have a Point field `default_center` and an IntegerField `default_zoom`, both on my User model, do something like this:

```
from django.template.response import TemplateResponse

def home_view(request):
    template = "pages/home.html"
    context = {}

    context["settings_overrides"] = {
        "DEFAULT_CENTER": (
            request.user.default_center_point.y,
            request.user.default_center_point.x,
        ),
        "DEFAULT_ZOOM": request.user.default_zoom,
    }

    return TemplateResponse(request, template, context)
```

and in the template:

`{% leaflet_map "main" settings_overrides=settings_overrides %}`

It's easy and effective, and no need to slog through custom js to customize the map.
