### ISSUE TITLE
Leaflet 1.3.4 is Released

### ISSUE THREAD

**Issue by askpatrickw** [makinacorpus/django-leaflet#223]
Leaflet 1.3.1 has just been released!
    This release fixes L.TileLayer regression, introduced in 1.3.0. Oops!
http://cdn.leafletjs.com/leaflet/v1.3.1/leaflet.zip

I might be able to do a PR this week.. but if not a nice easy PR for someone else. ;-)

**Comment by W7PEA** [comment]
1.3.2 is out now
https://leafletjs.com/2018/07/17/leaflet-1.3.2.html

**Comment by W7PEA** [comment]
And then 1.3.3... they're busy over there

https://leafletjs.com/2018/07/18/leaflet-1.3.3.html

**Comment by W7PEA** [comment]
hey @Gagaro  I was going to do a PR for 1.3.3 and I noticed that the leaflet files are in /leaflet/static and /leaflet/static/leaflet. Are they both necessary or should one be removed.

Thanks!

**Comment by Gagaro** [comment]
The leaflet folder is a mistake and should be removed. Thanks for the comment.

**Comment by W7PEA** [comment]
Leaflet 1.3.4 is Released

**Comment by claudep** [comment]
This ticket is obsolete as this package is now using leaflet 1.6.
