### ISSUE TITLE
First argument in 'static' must be 'as'

### ISSUE THREAD

**Issue by EmaCrzz** [makinacorpus/django-leaflet#224]
I have a line in the library that generates an error in django 1.11.14
It can be something internal my configuration.
In templates/leaflet/css.htm and templates/leaflet/js.html the line
{% load static from staticfiles %}
If I modify it by {% load static %} everything runs normally.

**Comment by W7PEA** [comment]
@EmaCrzz FYI: I think PR #225  fixed this.
