### ISSUE TITLE
Incorporate leaflet-hash?

### ISSUE THREAD

**Issue by mradamcox** [makinacorpus/django-leaflet#227]
I'm wondering if any thought or interest has gone into the idea of incorporating [leaflet-hash](https://github.com/mlevans/leaflet-hash), or something like it, into django-leaflet (as a configuration option, perhaps).

I have not used leaflet-hash, but it looks like a useful addition to almost any leaflet map, and it would be great to have an easy way to add it to a django-leaflet project.

**Comment by W7PEA** [comment]
Can't you use the plugin framework to use leaflet-has?

**Comment by mradamcox** [comment]
I haven't tried, but will when I get a chance. I was assuming that django's url philosophy may not play well with leaflet-hash.

**Comment by Gagaro** [comment]
The hash and get parameters are not taken into account with the Django URLs, it should be safe to use.

**Comment by mradamcox** [comment]
Finally got a chance to incorporate this into a project, and using the existing plugin framework worked like a charm.

1. downloaded leaflet-hash.js from https://github.com/mlevans/leaflet-hash

2.  `settings.py`

        LEAFLET_CONFIG = {
            ...etc...
            'PLUGINS': {
                'leaflet-hash': {
                    'css': [],
                    'js': STATIC_URL + 'plugins/leaflet-hash.js',
                    'auto-include': True,
                },
            }
        }

3. `mymap.js`

        var map = L.map('map');
        var hash = new L.Hash(map);

Closing this ticket now.
