### ISSUE TITLE
Test on recent version of PostgreSQL

### ISSUE THREAD

**Issue by askpatrickw** [makinacorpus/django-leaflet#231]
I'm sure this project is not that dependent on the PostgreSQL version, but I am planning some upgrades and want to help-out where I can across my project dependencies so we're all staying current on the test matrix.

Currently django-leaflet is only testing on on 9.6.2
Latest 9.6 version is 9.6.10
Latest major version is 10.5

Django GIS supports 9.3+
https://docs.djangoproject.com/en/2.0/ref/contrib/gis/install/#requirements

I propose changing 9.6.2 to 9.6.10 and adding 10.5

I'm happy to to make the PR, but I'd like to get feedback on this first to prevent the many CI runs I caused with PR #229

**Comment by Gagaro** [comment]
I'm not sure we should test on both version. The fields should already be tested in Django with different psql versions and this would double our tests duration. Unless you see another reason to do it.

You can upgrade the version though, no problem there.

**Comment by W7PEA** [comment]
Hey @Gagaro  Just to clarify... are you saying to update to version 10 or just the latest 9.6 release?
tx!

**Comment by Gagaro** [comment]
Either one of them.

**Comment by claudep** [comment]
Travis is currently using PostgreSQL 10. I don't think adding more versions is so much useful. I'd suggest to close this.
