### ISSUE TITLE
TypeError - super() takes at least 1 argument

### ISSUE THREAD

**Issue by TastyMuffins** [makinacorpus/django-leaflet#238]
Error occured when loading the admin 'mixin' I belive. Error occurs @ url http://localhost:8000/admin/mushrooms/mushroomspot/add/
Screenshots attached.

Request Method: | GET
-- | --
http://localhost:8000/admin/mushrooms/mushroomspot/add/
1.11.16
TypeError
super() takes at least 1 argument (0 given)
C:\Python27\lib\site-packages\leaflet\forms\backport.py in get_context, line 202
C:\Python27\python.exe
2.7.12
['C:\\Users\\MYUSERNAME\\Desktop\\Code\\django-leaflet\\example',  'C:\\WINDOWS\\SYSTEM32\\python27.zip',  'C:\\Python27\\DLLs',  'C:\\Python27\\lib',  'C:\\Python27\\lib\\plat-win',  'C:\\Python27\\lib\\lib-tk',  'C:\\Python27',  'C:\\Python27\\lib\\site-packages',  'C:\\Python27\\lib\\site-packages\\win32',  'C:\\Python27\\lib\\site-packages\\win32\\lib',  'C:\\Python27\\lib\\site-packages\\Pythonwin']
Mon, 15 Oct 2018 18:13:49 +0000
![image](https://user-images.githubusercontent.com/9805186/46969840-90449e80-d074-11e8-91f6-bb937cf5f2b1.png)

**Comment by claudep** [comment]
`backport.py` is no more, I'd suggest closing this ticket.

**Comment by Gagaro** [comment]
Yes, too old unfortunately.
