### ISSUE TITLE
Map not displayed in mobile browser

### ISSUE THREAD

**Issue by Rajkumar55** [makinacorpus/django-leaflet#241]
Map is not displayed in Django admin page in mobile browser. It is shown as a blank area.

**Comment by chiangbt** [comment]
i find thie bug, but i don't know how to solved it!!1

**Comment by markfoleyie** [comment]
Issue seems to be that somewhere in the CSS the width of the map widget is set to zero when screen width is less  than 768px. It looks like the map widget cannot display below width 688px. This is only an issue when using **LeafletGeoAdmin**, when I create a page with a map widget using a Django template in the usual way, everything works fine. Maybe there's a setting that I'm missing but, for the life of me, I can't find it.

I've compared the CSS generated for the admin page and standard page and can't spot anything that would make a difference. Any help on this would be much appreciated.

**Comment by mRokita** [comment]
It's probably a bit too late, but that's a workaround for this issue:

```python
@admin.register(MyModel)
class MyModelAdmin(LeafletGeoAdmin):
     map_width = 'min(calc(100vw - 30px), 720px)'
```
