### ISSUE TITLE
Has anyone managed to get this to work?

### ISSUE THREAD

**Issue by ursomniac** [makinacorpus/django-leaflet#242]
I've spent three days trying to get this to work.   The included example doesn't work, and the installation instructions apparently assume you already have it working.

If anyone can point me to better documentation, I'd greatly appreciate it.

**Comment by marzukia** [comment]
I realise I'm 7 months late to your response. However, for any future readers I've detailed my implementation below.

I've managed to get it working using Django / PostGIS for the backend and leaflet to render GeoJSON. Simplified example below.

```
    $(window).on('map:init', function (e) {
        let detail = e.originalEvent ?
                    e.originalEvent.detail : e.detail;

    let geoLayer = L.geoJSON({{ data }})

    geoLayer.addTo(detail.map);    
    })
```

**Comment by OmenApps** [comment]
Since the issue author provided zero context and never provided further response, this issue could probably be closed out. Many people (myself included) are successfully using django-leaflet.

**Comment by Gagaro** [comment]
I agree.
