### ISSUE TITLE
Make map widget raw textarea size configurable

### ISSUE THREAD

**Issue by florianm** [makinacorpus/django-leaflet#247]
Would it be possible to configure the width of the raw geometry field of the map widget, rather than hard code?

The line [here](https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/templates/leaflet/widget.html#L45) reads:
```
<textarea id="{{ id_css }}" class="required" cols="150" rows="10" name="{{ name }}">{{ serialized }}</textarea>
```

Two approaches:

* Give it a unique combination of CSS classes to set the width for
* `cols="{% if raw_cols %}{{ raw_cols }}{% else %}150{% endif %}"` - maybe similar for rows

Currently, the hard-coded width busts my form layouts. Otherwise, great to have a "paste your GeoJSON" option!

**Comment by florianm** [comment]
Here's a hack to override the raw textarea width with a custom `admin/change_form.html`:

```
{% extends "admin/change_form.html" %}
{% load i18n admin_urls staticfiles leaflet_tags %}

{% block stylesheets %}
{{ block.super }}
{% leaflet_css plugins="draw,forms" %}
<!-- Fix missing favicon -->
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
<style>
/* Force leaflet controls underneath header (z-index 1000) and above leaflet tiles (z-index 400)*/
.leaflet-top{z-index:999;}

/* https://github.com/makinacorpus/django-leaflet/issues/247 */
textarea.required {width:100%;}
</style>
{% endblock %}
```

**Comment by Gagaro** [comment]
Hi, feel free to do a PR. I'll gladly review/merge it.

**Comment by florianm** [comment]
@gagaro cheers, will send a PR. How about dropping the cols/rows and giving the textarea.required a unique css class?

e.g. 
```
<textarea id="{{ id_css }}" class="required django-leaflet-raw-textarea" name="{{ name }}">{{ serialized }}</textarea>
```
Do we need a default style, and if so, where would be a good place? Next to [map_css](https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/templates/leaflet/widget.html#L4)?

**Comment by Gagaro** [comment]
Or even inside the `map_css` block, so it is easy to overwrite it if needed.

**Comment by florianm** [comment]
I'll figure that out when I fork and work on it (ETA early next week), but will user CSS override styles in `map_css`?

**Comment by Gagaro** [comment]
No because the CSS in `map_css` would be after the user CSS, unless `!important` is used.
