### ISSUE TITLE
leaflet.draw

### ISSUE THREAD

**Issue by Omenranr** [makinacorpus/django-leaflet#253]
Hello, I want to use leaflet drawing tool. But it seems that the only way to use it is in a form. Is there a way to use it without forms. Thanks

**Comment by Gagaro** [comment]
Hi, you can add leaflet.draw lile any other plugins: https://django-leaflet.readthedocs.io/en/latest/templates.html#plugins

**Comment by Omenranr** [comment]
Ok thanks
