### ISSUE TITLE
Add request to formfield_to_dbfield

### ISSUE THREAD

**Issue by Rikuoja** [makinacorpus/django-leaflet#260]
In v1.10, Django updated the signature of `formfield_to_dbfield` (https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/admin.py#L29) to contain `request`, but django-leaflet still does not pass request on.

As libraries such as https://github.com/deschler/django-modeltranslation/ have recently noticed this and fixed the signature accordingly (https://github.com/deschler/django-modeltranslation/issues/510), django-leaflet can no longer be used in combination with those, until the corresponding fix is implemented here.

**Comment by Gagaro** [comment]
Hi,

Thanks for the report, feel free to do a PR and I'll gladly review it.

**Comment by Gagaro** [comment]
0.25.0 has been released with this fix.
