### ISSUE TITLE
support to Django 3.0

### ISSUE THREAD

**Issue by domdinicola** [makinacorpus/django-leaflet#265]

**Comment by Zouhuo** [comment]
**for the time, the solution:**
**file leaflet/__init__.py:**
replace line 21 -> from django.templatetags.static import static
replace line 23 -> import six
**file leaflet/templatetags/leaflet_tags.py:**
replace line 8 -> import six

**Comment by Gagaro** [comment]
Released in 0.26.0 thanks to #266 and @igor-yamshchykov .
