### ISSUE TITLE
Map widget contains link to geojsonlint.com which shows inappropriate ads

### ISSUE THREAD

**Issue by florianm** [makinacorpus/django-leaflet#297]
The map widget has a helptext with a link ([code](https://github.com/makinacorpus/django-leaflet/blame/master/leaflet/templates/leaflet/widget.html#L47)) to https://geojsonlint.com/, which shows clickbaity ads. These ads have been reported to me as inappropriate by some of my users who don't have adblockers installed.

Since I have PR'd this link to the repo, would you accept a PR replacing the link with https://geojson.io/#map=2/20.0/0.0 or any other online geojson validator?

**Comment by Gagaro** [comment]
Yes I agree, please do the PR and I'll merge it and do a release.

**Comment by Gagaro** [comment]
0.27.1 has been released with the fix. Thanks for the report and the PR :+1: .

**Comment by florianm** [comment]
The new release works as expected. Many thanks for the quick turn-around and merge!
