### ISSUE TITLE
Move away from Travis CI

### ISSUE THREAD

**Issue by claudep** [makinacorpus/django-leaflet#310]
Unfortunately, Travis CI is no longer really usable for open source software (you can find the story by searching the Web). Most projects are now moving to GitHub actions instead.
Looks like my latest PR (#309) did'nt even trigger a travis build.

**Comment by Gagaro** [comment]
Yes I'm aware of that but still didn't have the time to take a look at how github actions actually work.

I'll take that time now and try to implement them for this repository.

**Comment by Gagaro** [comment]
All right it is up and running. I'm not sure how to run it for your PR though.

If anyone have ideas on how to improve it, don't hesitate to do a PR.

**Comment by Gagaro** [comment]
Maybe you need to have the workflow file in your fork for it to work.

**Comment by claudep** [comment]
Don't worry, I'll rebase it and it should run. Thanks a lot for the migration!
