### ISSUE TITLE
Leaflet Form Widget inside a django MultiWidget

### ISSUE THREAD

**Issue by jnsdrtlf** [makinacorpus/django-leaflet#322]
We are currently using the [Leaflet widget](https://django-leaflet.readthedocs.io/en/latest/widget.html#in-forms) inside of a [django MultiWidget](https://docs.djangoproject.com/en/dev/ref/forms/widgets/#django.forms.MultiWidget). The problem is that the `get_context` method of the MultiWidget only passes the `widget` context of any of the subwidgets to the context:

```python
subwidgets.append(widget.get_context(widget_name, widget_value, widget_attrs)['widget'])
```
(can be found [here](https://github.com/django/django/blob/3fec16e8acf0724b061a9e3cce25da898052bc9b/django/forms/widgets.py#L846))

Thus, crucial parts of the context (e.g. `module`) will be missing when rendering the widget's template. Basically, all additional context attributes from the [`LeafletWidget._get_attrs(name, ...)`](https://github.com/makinacorpus/django-leaflet/blob/e9b71ae2017689767eadbfd0db682a94c2e8d3e3/leaflet/forms/widgets.py#L33) method are missing from the context.

The way we solve this is by replicating the fields from `_get_attrs` in the `get_context` method of our custom `MultiWidget`. However, this is very inconvenient and might break with future updates.

I was wondering if we could either

 1) Make `_get_attrs` public by removing the underline at the beginning of the method name. This way, it would be easy to get all additional context attributes that are required for the widget to work in custom widgets.

 2) Put crucial attributes that are **required by the widget's template** into the `widget` attribute.

The first option would hopefully introduce the least breaking changes as private methods should not be used much outside of this project. However, there is of course the possibility that someone uses this method in a custom widget that inherits from this widget. In such a case, an alias `_get_attrs = get_attrs` should be sufficient (?). The later option would probably be the most consistent and cleanest approach. However, it would most definitely introduce more breaking changes.

What do you think? Is this out of the scope of the LeafletWidget? Of course I can implement the changes and submit a pull request but I first wanted to discuss the most sensible approach. Or am I missing something completely?

**Comment by jnsdrtlf** [comment]
It turned out that there are 3 more fields or attributes that are required for the widget to render or work properly:

 - `serialized`
 - `geom_type`
 - `name`

(`module` too, but it is overwritten by `_get_attrs` anyway).

All those attributes are set in the [`BaseGeometryWidget.get_context`](https://github.com/django/django/blob/3fec16e8acf0724b061a9e3cce25da898052bc9b/django/contrib/gis/forms/widgets.py#L44) method. 

Note that all context variables that are not inside the `widget` field will not be passed when using the MultiWidget class. 

Considering this, option 2. from my original comment seems to make less sense, as django itself also does not put these fields inside of the `widget` field. When I think about it, the `widget` field is also not be the right location for these attributes. It is generally used for the attributes of an HTML tag (e.g. `<input name="{{ widget.name }}">`).

Making the `_get_attrs` method public will still help the cause.

**Comment by Gagaro** [comment]
Feel free to do a PR with the changes. We should have an alias from `_get_attrs` to the new method with a deprecation warning.

**Comment by jnsdrtlf** [comment]
Thanks for the response. I'll see when I have the time to prepare the PR.

**Comment by jnsdrtlf** [comment]
Sorry that it took me so long. I finally came around to create a pull request (#326).
