### ISSUE TITLE
Add zoomSnap and zoomDelta to initial options

### ISSUE THREAD

**Issue by kgeographer** [makinacorpus/django-leaflet#330]
Hello,
I see that #193 and the response are related to my question, but I don't see how to actually implement the addition of options. 

My initialization tag is `{% leaflet_map "map_search" callback="map_init" %}` and I do a lot within the map_init function and elsewhere with javascript, but I can't tell how the code referenced below can be used to insert the zoomSnap and zoomDelta options I need for finer control of zoom. I was hoping for something like `{% leaflet_map "map_search" callback="map_init" options={"zoomSnap":0.5} %}`. 

Can you help?
thx

> You can subscribe on the 'map:init' event to get the map once it has been initialized: https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/static/leaflet/leaflet.extras.js#L228

_Originally posted by @Gagaro in https://github.com/makinacorpus/django-leaflet/issues/193#issuecomment-301009842_

**Comment by Gagaro** [comment]
You can change options of the map with `map.options.zoomSnap = 0.5`.

But I agree adding an `options` parameters would be better. This could be done by adding options here https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/templatetags/leaflet_tags.py#L57-L59, then adding it to `djoptions` https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/templatetags/leaflet_tags.py#L100 and finally including it there https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/static/leaflet/leaflet.extras.js#L60

**Comment by kgeographer** [comment]
Thank!. Slipped my mind I could get at it with map.options. If there's any performance hit it's not at all noticeable.
