### ISSUE TITLE
Default marker icon is not showing in prod environment

### ISSUE THREAD

**Issue by Bakhtiyar-Garashov** [makinacorpus/django-leaflet#342]
It seems default marker icon path is somehow ruined when deploying app to production. The same issue which is described here https://stackoverflow.com/questions/41144319/leaflet-marker-not-found-production-env

<img width="870" alt="Screenshot 2021-09-05 at 01 05 09" src="https://user-images.githubusercontent.com/48382094/132109083-8581256e-f5de-4962-98e6-0c044430b116.png">

More about issue with original Leaflet project : https://github.com/Leaflet/Leaflet/issues/4968

**Comment by Gagaro** [comment]
See https://github.com/Leaflet/Leaflet/issues/4968#issuecomment-483402699 for possible solutions.
