### ISSUE TITLE
Working with inlines

### ISSUE THREAD

**Issue by josepsitjar** [makinacorpus/django-leaflet#352]
In the Django Admin, the leaflet map is not initialized when used as inline a model with a geom field. 
Until the new object is saved and the page refreshed, the geom field appears as textarea. 
Is there any solution for that?

Thanks!

**Comment by AL9000** [comment]
@josepsitjar Thank you for reporting this, I was able to reproduce and in fact, the workaround is to refresh the page after the new object is saved.
I may work on this but maybe not in the near future, so feel free to do a PR :)

**Comment by josepsitjar** [comment]
Thanks for your answer @AL9000
