### ISSUE TITLE
Django 4 and Python 3.10 support?

### ISSUE THREAD

**Issue by cfshufeldt** [makinacorpus/django-leaflet#353]
We use this package with both Python 3.10 and Django 4 without issue. Would it be appropriate to open a pull request to add testing on this combination of Python and Django in the CI workflow? If so, I would be happy to write such a pull request.

**Comment by Gagaro** [comment]
Sure, go ahead, I'll gladly review it :+1: .

**Comment by thisisanameforsure** [comment]
@cfshufeldt Please do!
