### ISSUE TITLE
Show labels to manually input coordinates

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [makinacorpus/django-leaflet#356]
Hi I'm looking for a way to manually input coordinates instead of dragging and dropping pins. I want both the map view and input fields. Anyone have a code snippet for admin or is this enabled by default? Specifically looking for point field (and maybe a snippet for admin page)

**Comment by Gagaro** [comment]
You can set `display_raw = True` on your `AdminModel` to have the textarea shown.

This is a variable in the widget template, so if you set it in the widget context it can work outside of admin too.

**Comment by VLunaa** [comment]
> You can set `display_raw = True` on your `AdminModel` to have the textarea shown.
> 
> This is a variable in the widget template, so if you set it in the widget context it can work outside of admin too.

Hey, how can I edit it in the AdminModel? How can I edit it in the widget context? I'm totally new in Django and this stuff, I'm just a student, please help me :)

**Comment by Gagaro** [comment]
When you create your own admin model, you can set a lot of things as attributes / methods. For example :

```python
class WeatherStationAdmin(LeafletGeoAdmin):
    display_raw = True
```
