### ISSUE TITLE
readme.md -> Tutorial link outdated

### ISSUE THREAD

**Issue by nottheend** [makinacorpus/django-leaflet#374]
Thanks for this nice project!

The tutorial link seems to be outdated in the readme of this repo:
http://[blog.mathieu-leplatre.info](http://blog.mathieu-leplatre.info/geodjango-maps-with-leaflet.html)/geodjango-maps-with-leaflet.html

**Comment by Gagaro** [comment]
Indeed, I removed this section. Thanks for the heads up.
