### ISSUE TITLE
Customize LeafletWidget map

### ISSUE THREAD

**Issue by rgreenemun** [makinacorpus/django-leaflet#78]
This is more of a conceptual question than an issue...

Have successfully used django-leaflet for read-only point display by following the concepts at https://github.com/makinacorpus/django-leaflet#usage. Have used both LEAFLET_CONFIG and the map_init js callback to heavily customize the map, including custom controls, marker icons, marker clusters, basemaps, overlays, etc.

Now editing point data and have successfully implemented the LeafletWidget with a PointField by following https://github.com/makinacorpus/django-leaflet#leaflet-map-forms-widgets, however am unsure how to go about customizing the map. What is the most straightforward way to edit data while having full control over the map initialization?

Thanks in advance,
Randal

**Comment by manu09** [comment]
@leplatrem Can you tell me where `YourApp.GeometryField` is initialized? I understand your instructions above but I can't seem to find the javascript on django-leaflet to actually create an object of `YourApp.GeometryField`.
