### ISSUE TITLE
Ascii decode error on install

### ISSUE THREAD

**Issue by oleiade** [makinacorpus/django-leaflet#82]
Hi!

I'm trying to pip install the library on ubuntu 14.04, in a virtualenv set up to use python3.3. And I end up with an ascii decode error thrown by the setup.py.

Here's the command I'm using to install:

``` bash
pip install --allow-all-external --no-input --exists-action=w -r requirements.txt
```

Here's the output:

``` bash
 Downloading/unpacking django-leaflet (from -r requirements.txt (line 33))
             Running setup.py (path:/home/blablabla/env/build/django-leaflet/setup.py) egg_info for package django-leaflet
               Traceback (most recent call last):
                 File "<string>", line 17, in <module>
                 File "/home/blablabla/env/build/django-leaflet/setup.py", line 19, in <module>
                   long_description=open(os.path.join(here, 'README.rst')).read() + '\n\n' +
                 File "/home/blablabla/env/lib/python3.3/encodings/ascii.py", line 26, in decode
                   return codecs.ascii_decode(input, self.errors)[0]
               UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 5022: ordinal not in range(128)
               Complete output from command python setup.py egg_info:
               Traceback (most recent call last):

             File "<string>", line 17, in <module>

             File "/home/blablabla/env/build/django-leaflet/setup.py", line 19, in <module>

               long_description=open(os.path.join(here, 'README.rst')).read() + '\n\n' +

             File "/home/blablablabla/env/lib/python3.3/encodings/ascii.py", line 26, in decode

               return codecs.ascii_decode(input, self.errors)[0]

           UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 5022: ordinal not in range(128)

           ----------------------------------------
           Cleaning up...

```

I'm not sure about the proper solution. Maybe casting the `long_description` variable input to `unicode` explicitly when we're using python3?

Let me know,
Thanks!

**Comment by valdemarrolfsen** [comment]
Still getting this error:

pip3.4 install --user django-leaflet

Collecting django-leaflet
  Downloading django-leaflet-0.16.0.zip (231kB)
    100% |################################| 233kB 1.6MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-w3of_1sh/django-leaflet/setup.py", line 19, in <module>
        long_description=open(os.path.join(here, 'README.rst')).read() + '\n\n' +
      File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14276: ordinal not in range(128)

I am running the newest version of pip

**Comment by olivierdalang** [comment]
Hi,
I have the same error here (on one of my ubuntu setups, not both, but they are both relatively vanilla ubuntu 14.04, so I don't know what's going on...)
Bests,
Olivier

**Comment by olivierdalang** [comment]
By removing the content of README.rst and CHANGES, the installation works, so it must be an easy bug to fix.

If you can't wait : `pip3 install -e git+https://github.com/olivierdalang/django-leaflet.git#egg=django-leaflet`

**Comment by leplatrem** [comment]
Yes, we might have to read those files using utf8 codec, as it is done here:
https://github.com/mozilla-services/cliquet/blob/master/setup.py

Would like to try it and open a pull request please?

**Comment by kostya0shift** [comment]
Workaround (ubuntu trusty minimal):
$ LC_ALL=C.UTF-8 pip3 install django-leaflet

**Comment by cleder** [comment]
`setenv LANG en_GB.UTF-8` solves this on freebsd with csh
