### ISSUE TITLE
Bad map initialization in the edit view

### ISSUE THREAD

**Issue by manelclos** [makinacorpus/django-leaflet#89]
Hi, we have a repeatable problem in which the geometry in the admin will be drawn incorrectly and also make the map unusable. Here is an screenshot to clearly describe the problem:

https://gist.github.com/manelclos/8e77100964ede40925b4#file-bad_map-png

Notice the zoom out is not usable and the background tiles are not loaded.

The code that produces the problem was introduced here: https://github.com/makinacorpus/django-leaflet/commit/652bcd02815df631d79076984058dcfd0aaa4e10#diff-bf6696ab3b9097246bc7835bc72bf4c6R188

    if (typeof(options.callback) == 'function') {
        setTimeout(function () {
            options.callback(map, options);
        }, 0);
    }

The problem seems to be that map.fitBounds() function will be called WHILE the leaflet map is still doing something else, like loading the tiles for the default level or whatever. This is a lot easier to catch with simple polygons and lines.

There are two ways of getting rid of the problem:
1) increase the delay of the timeout to 1000 ms, this way it is called after everything else has happened and the problem does not show.

    if (typeof(options.callback) == 'function') {
        setTimeout(function () {
            options.callback(map, options);
        }, 1000);
    }

2) remove the setTimeout wrapper and call the callback directly. This seems to work without producing any side effect.

    if (typeof(options.callback) == 'function') {
            options.callback(map, options);
    }

Obviously I'd go for the second solution. Is there any reason why this call is deferred instead of being called directly?

**Comment by leplatrem** [comment]
I don't remember anything particular, except running the callback when first level of initialization is done.
I would go for the second solution too, or rely on some leaflet initialization event maybe...

**Comment by manelclos** [comment]
Yes, that makes sense. I've taken a look at the API, and the load event is the one that comes closer (http://leafletjs.com/reference.html#map-load). Still, it may produce some double "set view" strange effect. As leaflet is constructing the map, I think second solution is best here.

I'll create the PR for review. Thanks!
