### ISSUE TITLE
Widget hangs forever

### ISSUE THREAD

**Issue by NotSqrt** [makinacorpus/django-leaflet#90]
Hi !

Just installed django-leaflet, no particular config.

With forms (either the admin with LeafletGeoAdmin, or my own form, with LeafletWidget) I encounter the following bug:
 * when editing a model with **empty** spatial informations, no problem, I can select a point and save successfully
 * when editing a model with spatial informations, the browser hangs forever when executing the JS (I can see the page, the Leaflet widget is partially loaded, ...). It fails at least on chrome on linux, and also on firefox, which tells me that it hanged on leaflet/leaflet-src.js line 710.

It seems to have broken between versions 0.14.2 and 0.15.0.

Any ideas ?

**Comment by leplatrem** [comment]
Thanks for reporting this. Could you please have a look at the JavaScript console and check if there is any errors ?

Indeed something changed about new records in 0.14.0 (multipoints)
* https://github.com/makinacorpus/django-leaflet/commit/4dc6ac0916c9a9bc8b277a2897980198d1c91d8e
* https://github.com/makinacorpus/django-leaflet/compare/0.13.7...0.14.0

**Comment by NotSqrt** [comment]
No logs in the console.

Firefox says leaflet-src.js is blocked at line 710 : https://github.com/makinacorpus/django-leaflet/blob/0.15.2/leaflet/static/leaflet/leaflet-src.js#L710 but I really don't see why ..

**Comment by dyve** [comment]
Same problem here.

**Comment by eloyfelix** [comment]
Same problem here, It's working for me from with 1.5.0 and 1.5.1 versions. 1.5.2 hangs. I also tried the dev 1.5.3 and it's hanging too.

**Comment by NotSqrt** [comment]
Strange, since it seems #95 fixed it for me. Don't forget to collectstatic / clear cache !

**Comment by dyve** [comment]
Not enough time to do a full test, but #95 seems to fix.

**Comment by kirpit** [comment]
well this is still happening to me. both with 0.15.2 and 0.15.3dev. on firefox, it says "Script: http://localhost:8000/static/leaflet/leaflet.js:7" unresponsive. I've been trying to debug for a few hours.

**Comment by NotSqrt** [comment]
There was a recent fix for similar issues in https://github.com/Leaflet/Leaflet/issues/2021
But it is not yet released ..

**Comment by siolag161** [comment]
Thanks for the nice plugin but I also encountered the same problem, it freezes the whole thing after eating up 2GB of my RAM.

**Comment by leplatrem** [comment]
Thanks for reporting.

If you're stuck you can try older versions of django-leaflet or give a try
to @Azimkhan contribution in #95.

**Comment by manelclos** [comment]
This should be the same issue #89 I'm having. See the issue for a possible workaround, it explains why older versions work ok.

**Comment by manelclos** [comment]
Just tried a fresh checkout. It hangs and after applying pull #95 everything works as expected. Will love a release with the fix included!
