### ISSUE TITLE
Admin Imports Need Updating for Django 1.8

### ISSUE THREAD

**Issue by dummerbd** [makinacorpus/django-leaflet#99]
There have been some changes in Django 1.8 relating to the `django.contrib.gis` library, which of course includes the `GeometryField` found in `django.contrib.gis.db.models` module.

I am using django-leaflet in a project that does not make use of GeoDjango (`django.contrib.gis`) and so we do not have GEOS, PostGIS, PROJ.4 and other required libraries installed. This hasn't prevented us from using django-leaflet until upgrading from Django 1.7.4 to 1.8.0.

The problem comes from django-leaflet's `admin.py` file:
```python
try:
    from django.contrib.gis.db.models import GeometryField
except ImportError:
    GeometryField = type(object)
```

In Django 1.8.0, this import statement raises an `ImproperlyConfigured` exception instead of an `ImportError` when GeoDjango isn't installed.

Unless I'm missing something here, this seems like a straightforward fix:
```python
try:
    from django.contrib.gis.db.models import GeometryField
except (ImportError, ImproperlyConfigured):
    GeometryField = type(object)
```

**Comment by leplatrem** [comment]
Thanks for this feedback! 

This change seems reasonnable :) Unfortunately I haven't much time to investigate, so we'll release and see what comes out :)

**Comment by dummerbd** [comment]
Awesome, thanks for the quick response!
